version: '3.8'


services:

  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/pb_data:/pb/pb_data
      - ./backend/pb_migrations:/pb/pb_migrations
    restart: always

  frontend:
    container_name: frontend
    image: ghcr.io/smd-ka/smd-ka/frontend:main
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always

  kings_cafe:
    container_name: kings_cafe
    image: ghcr.io/smd-ka/smd-ka/kings_cafe:main
    build:
      context: ./kings-cafe
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - smd_ka_network

  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2.8
    environment:
      DOMAIN_LONG: ${DOMAIN_LONG:-smd-karlsruhe.de}
      DOMAIN_SHORT: ${DOMAIN_SHORT:-smd-ka.de}
      PR_NUMBER: ${PR_NUMBER:-0}
      DOMAIN_KINGS_CAFE: ${DOMAIN_KINGS_CAFE:-kings-cafe.de}
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy_config:/config
      - caddy_data:/data
    restart: always




volumes:
  caddy_config:
  caddy_data:
