version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    volumes:
      - type: bind
        source: ./backend/pb_data
        target: /pb/pb_data

    restart: always
    networks:
      - smd_ka_network

  frontend:
    container_name: frontend
    image: ghcr.io/smd-ka/smd-ka/frontend:main
    restart: always
    networks:
      - smd_ka_network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        - webdata:/usr/share/nginx/html
        - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
     - backend
    restart: always
    networks:
      - smd_ka_network

  
  
  
  
  letsencrypt:
    container_name: letsencrypt
    image: gordonchan/auto-letsencrypt
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webdata:/usr/share/nginx/html
    environment:
      - EMAIL=webmaster@smd-karlsruhe.de
      - SERVER_CONTAINER=nginx
      - WEBROOT_PATH=/usr/share/nginx/html
      - DOMAINS=api.smd-ka.de www.smd-ka.de smd-ka.de
      - CHECK_FREQ=7
    restart: always
  
  
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webdata:/usr/share/nginx/html


networks:
  smd_ka_network:
    driver: bridge

volumes:
  letsencrypt:
  webdata: