version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    volumes:
      - type: bind
        source: ./backend/pb_data
        target: /pb/pb_data

    restart: always
    networks:
      - smd_ka_network


  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/certs:/etc/nginx/certs
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/html:/usr/share/nginx/html 

    ports:
      - 80:80
      - 443:443
    links:
     - backend
    restart: always
    networks:
      - smd_ka_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  smd_ka_network:
    driver: bridge
