version: '3.8'

services:
  # PR Backend service
  backend:
    image: ghcr.io/your-repo/backend:pr-${PR_NUMBER}  # Use PR-specific image tag
    container_name: backend-pr-${PR_NUMBER}  # Unique container name for PR
    environment:
      - NODE_ENV=staging  # Staging environment for PR
    ports:
      - "8081:3000"  # Use a different port for PR backend
    networks:
      - pr

  # PR Frontend service
  frontend:
    image: ghcr.io/your-repo/frontend:pr-${PR_NUMBER}  # Use PR-specific image tag
    container_name: frontend-pr-${PR_NUMBER}  # Unique container name for PR
    environment:
      - NODE_ENV=staging  # Staging environment for PR
    ports:
      - "8082:8080"  # Use a different port for PR frontend
    networks:
      - pr

networks:
  pr:
    driver: bridge