version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    volumes:
      - type: bind
        source: ./backend/pb_data
        target: /pb/pb_data

    restart: always
    networks:
      - smd_ka_network


  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        
    ports:
      - 80:80
      - 443:443
    links:
     - backend
    restart: always
    networks:
      - smd_ka_network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html  
    # entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'


networks:
  smd_ka_network:
    driver: bridge
