version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    volumes:
      - type: bind
        source: ./backend/pb_data
        target: /pb/pb_data

    restart: always
    networks:
      - smd_ka_network


  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
    links:
     - backend
    restart: always
    networks:
      - smd_ka_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  smd_ka_network:
    driver: bridge

volumes:
  pb_data:
    name: pb_data 