version: '3.8'


services:

  backend:
    container_name: backend
    image: ghcr.io/smd-ka/smd-ka/backend:main
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/pb_data:/pb/pb_data
      - ./backend/pb_migrations:/pb/pb_migrations
    networks:
      - default
    restart: always

  frontend:
    container_name: frontend
    image: ghcr.io/smd-ka/smd-ka/frontend:main
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - default
    restart: always

  kings_cafe:
    container_name: kings_cafe
    image: ghcr.io/smd-ka/smd-ka/kings_cafe:main
    build:
      context: ./kings-cafe
      dockerfile: ./Dockerfile
    networks:
      - default
    restart: always

  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2.8
    environment:
      DOMAIN_LONG: ${DOMAIN_LONG:-smd-karlsruhe.de}
      DOMAIN_SHORT: ${DOMAIN_SHORT:-smd-ka.de}
      PR_NUMBER: ${PR_NUMBER:-0}
      DOMAIN_KINGS_CAFE: ${DOMAIN_KINGS_CAFE:-kings-cafe.de}
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - default
      - caddy_net
    extra_hosts:
      - "caddy-net.docker.internal:172.31.255.1"
    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy_config:/config
      - caddy_data:/data
    restart: always


networks:
  default:
    driver: bridge

  # network for other docker-composes to attach to
  # how to use this network: 2 possibilities (mostly independent from each other)
  #   1. bind internally like Authentik
  #     - (usually requires control over docker-compose of that service)
  #     - throw service container in this network
  #     - do NOT add a "ports:" binding to that container
  #     - instead, give that container an unique alias
  #     - in the Caddyfile, use that alias to reach the service
  #   2. bind externally like Nextcloud AiO
  #     - (only requires control over external/"public" Docker "ports:" bindings)
  #     - do NOT add the service container to this network
  #     - choose a not occupied port from the list below per service
  #     - add a "ports:" binding for the service container, binding to "<caddy_net-host_ip>:<port>",
  #       e.g. ports: [ "172.31.255.1:8080" ]
  #     - in the Caddyfile, refer to the same host binding (there is an alias for that IP) to reach the service
  caddy_net:
    name: caddy_net
    driver: bridge
    attachable: true  # allow containers outside any compose to attach
    ipam:
      config:
        # static IP range important for static IP of docker host
        - subnet: 172.31.255.0/24
          gateway: 172.31.255.1  # <- IP of docker host in that network
    # List of Ports on Host IP:


volumes:
  caddy_config:
  caddy_data:
