version: '3.8'

services:
  backend:
    image: ghcr.io/smd-ka/smd-ka/backend:main
    volumes:
      - pb_data:/pb/pb_data

    restart: always

    ports:
      - 8090:8090


  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    links:
     - backend
    restart: always

volumes:
  pb_data:
    name: pb_data 